### PR TITLE
BNB Testnet support (#145)

### PR DESCRIPTION
**Pull request by zerodouglas**
This addition adds the BNB (Binance Smart Chain) RPC endpoint to chain ID 97 as described in #145 . Will need further discussion with @douglance .

### CODE REVIEW

**Comment by douglance** [comment]
It should already be available on the frontend. See chains list here: https://github.com/GridPlus/phonon-app/blob/3a941e7ad284f5e29392d64c59d132b32be59d37/src/constants/chains.ts

Let me know if it doesn't work.

**Comment by maevyn11** [comment]
Change looks like it should be right to me codewise. Has it been tested with the frontend to confirm deposits and redeems work with BSC?

**Comment by zerodouglas** [comment]
Yes, I tested and you can indeed create a phonon on the BSC testnet. The confirmation and history appears with MetaMask and I can indeed redeem.

**Comment by maevyn11** [comment]
@zerodouglas Closing this one in favor of the new PR?

**Comment by zerodouglas** [comment]
Yes this can be closed in favor of the new PR along with the new branch.

**Pull request closed without merging**
