### PR TITLE
Am/phonon transaction diagram

### PR DESCRIPTION
**Pull request by italianst4**
adding a WIP diagram for the anatomy of a phonon transaction.

### CODE REVIEW

**Review by npmaile — CHANGES_REQUESTED** [review]
Put this in a directory called contributing, and move the existing contributing.md file in there

**Comment by italianst4** [comment]
Done and done. I also updated the README.md with a reference to contributing.

**Comment by npmaile** [comment]
change this to target beta please

**Comment by italianst4** [comment]
I changed this to be merged into `Beta`.

**Pull request merged**
